# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
        name: Checkout
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore NuGet Packages
        run: msbuild -t:restore src\bonsai\Bonsai.sln

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.x

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Build Documentation
        run: dotnet docfx docfx.json
          
      - name: Checkout gh-pages
        uses: actions/checkout@v4.1.1
        with:
          ref: gh-pages
          path: gh-pages
      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true